/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MaquinaTragaMonedas.app.mvc.View;

import MaquinaTragaMonedas.app.mvc.Controller.ControladorMaquina;
import MaquinaTragaMonedas.app.mvc.Model.Maquina;
import java.awt.Dimension;
import java.awt.event.*;
import java.util.Random;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;
import javax.swing.*;
import javax.swing.Timer;

/**
 *
 * @author capis y heber
 */
public class UIMaquina extends javax.swing.JFrame {

    Maquina datosMaquina = new Maquina();
    ControladorMaquina controlador = new ControladorMaquina(datosMaquina);
    int valorApuesta = 0;
    int monedasDisponibles = 0;
    int gananciaApuesta = 0;

    /**
     * Creates new form UIMaquina
     */
    public UIMaquina() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Máquinita de la Esquina");
        this.setSize(new Dimension(600, 430));
        this.setLocationRelativeTo(null);
        //this.checkBoxPassword.setIcon(imagenCheckBoxDeseleccionado);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTxtApuesta = new javax.swing.JTextField();
        jBtnApuesta = new javax.swing.JButton();
        jTxtIngresoCredito = new javax.swing.JTextField();
        jBtnIngresoCreditos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        labelCarrete2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        labelCarrete3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        labelCarrete1 = new javax.swing.JLabel();
        jLabelCreditos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 350));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 120, 400));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 400));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 184, 16));
        jLabel1.setText("MAQUINITA DE LA ESQUINA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 350, 60));

        jPanel4.setBackground(new java.awt.Color(239, 184, 16));

        jTxtApuesta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jBtnApuesta.setBackground(new java.awt.Color(255, 255, 255));
        jBtnApuesta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnApuesta.setForeground(new java.awt.Color(0, 0, 0));
        jBtnApuesta.setText("Go!");
        jBtnApuesta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApuestaActionPerformed(evt);
            }
        });

        jTxtIngresoCredito.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jBtnIngresoCreditos.setBackground(new java.awt.Color(255, 255, 255));
        jBtnIngresoCreditos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnIngresoCreditos.setForeground(new java.awt.Color(0, 0, 0));
        jBtnIngresoCreditos.setText("Guardar Monedas");
        jBtnIngresoCreditos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnIngresoCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresoCreditosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingreso de apuesta:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingreso de créditos:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIngresoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnIngresoCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnApuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnApuesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtIngresoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnIngresoCreditos))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 350, 150));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setPreferredSize(new java.awt.Dimension(110, 90));

        labelCarrete2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelCarrete2.setForeground(new java.awt.Color(0, 0, 0));
        labelCarrete2.setText("...");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelCarrete2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelCarrete2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 130));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelCarrete3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelCarrete3.setForeground(new java.awt.Color(0, 0, 0));
        labelCarrete3.setText("...");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelCarrete3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelCarrete3)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 130));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setPreferredSize(new java.awt.Dimension(110, 85));

        labelCarrete1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelCarrete1.setForeground(new java.awt.Color(0, 0, 0));
        labelCarrete1.setText("...");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelCarrete1)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelCarrete1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 23, -1, 130));

        jLabelCreditos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelCreditos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCreditos.setText("....");
        jPanel5.add(jLabelCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Monedas Disponibles:");
        jLabel9.setToolTipText("");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 350, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApuestaActionPerformed
        if (!(jTxtApuesta.getText().isEmpty()) && datosMaquina.getHandel()) {
            monedasDisponibles = Integer.parseInt(jLabelCreditos.getText());
            valorApuesta = conversionMonedas(jTxtApuesta.getText());
            if (monedasDisponibles >= valorApuesta) {
                // Inicializamos el Timer para la animación de los símbolos
                this.jBtnApuesta.setEnabled(false);
                monedasDisponibles = monedasDisponibles - valorApuesta;
                jLabelCreditos.setText(String.valueOf(monedasDisponibles));
                datosMaquina.setValorApuesta(valorApuesta);
                jTxtApuesta.setText(null);                
                Timer timer = new Timer(100, new ActionListener() {
                    int contador = 0;
                    Random random = new Random();

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        // Actualizamos los JLabels nombrado con símbolos aleatorios durante la animación
                        labelCarrete1.setText(datosMaquina.getSimbolos()[random.nextInt(datosMaquina.getSimbolos().length)]);
                        labelCarrete2.setText(datosMaquina.getSimbolos()[random.nextInt(datosMaquina.getSimbolos().length)]);
                        labelCarrete3.setText(datosMaquina.getSimbolos()[random.nextInt(datosMaquina.getSimbolos().length)]);
                        
                        contador++;

                        if (contador >= 20) { // Detenemos la animación después de 20 ciclos
                            ((Timer) e.getSource()).stop();

                            // Usamos el método asíncrono para obtener el resultado final
                            Future<String[]> futureResultado = controlador.girarCarretesSimultaneamente();

                            try {
                                // Mostramos el resultado final en los JLabels
                                String[] resultadoFinal = futureResultado.get(); // Bloquea hasta que obtenga el resultado
                                labelCarrete1.setText(resultadoFinal[0]);
                                labelCarrete2.setText(resultadoFinal[1]);
                                labelCarrete3.setText(resultadoFinal[2]);

                                // Calculamos las ganancias aquí después de obtener el resultado
                                controlador.calcularGanancias(resultadoFinal);

                                // Verificamos si hay ganancias
                                if (datosMaquina.getGananciasApuesta() > 0) {
                                    gananciaApuesta = datosMaquina.getGananciasApuesta();
                                    JOptionPane.showMessageDialog(null, "Felicidades, has ganado " + gananciaApuesta + " monedas", "Juego Ganado", JOptionPane.INFORMATION_MESSAGE);
                                    monedasDisponibles = monedasDisponibles + gananciaApuesta;
                                    jLabelCreditos.setText(String.valueOf(monedasDisponibles));                                    
                                }
                            } catch (InterruptedException | ExecutionException ex) {
                                JOptionPane.showMessageDialog(null, "Ocurrió un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    }                  
                });
                timer.start(); // Inicia la animación
            } else {
                JOptionPane.showMessageDialog(null, "Monedas insuficientes para jugar", "Estado insuficiente de monedas", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingresar apuesta para jugar", "Ingreso de Monedas", JOptionPane.INFORMATION_MESSAGE);
        }
        jBtnApuesta.setEnabled(true);
    }//GEN-LAST:event_jBtnApuestaActionPerformed

    private void jBtnIngresoCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresoCreditosActionPerformed
        if (!(jTxtIngresoCredito.getText().isEmpty())) {
            datosMaquina.setHandel(true);
            // Se agregan los válores al Label correspondiente
            monedasDisponibles = conversionMonedas(jTxtIngresoCredito.getText());
            jLabelCreditos.setText(String.valueOf(monedasDisponibles));
            jTxtIngresoCredito.setText(null);
            return;
        }
        JOptionPane.showMessageDialog(null, "Ingrese sus monedas por favor, para poder jugar", "Ingreso de Monedas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBtnIngresoCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIMaquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApuesta;
    private javax.swing.JButton jBtnIngresoCreditos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCreditos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtApuesta;
    private javax.swing.JTextField jTxtIngresoCredito;
    private javax.swing.JLabel labelCarrete1;
    private javax.swing.JLabel labelCarrete2;
    private javax.swing.JLabel labelCarrete3;
    // End of variables declaration//GEN-END:variables
    public int conversionMonedas(String numero) {
        int numeroMonedas = 0;
        try {
            numeroMonedas = Math.abs(Integer.parseInt(numero));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "No se logro convertir correctamente: " + numero + " a número", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return numeroMonedas;
    }

}
